import Link from 'next/link'
import Navbar from '@/components/layout/Navbar'
import Footer from '@/components/layout/Footer'

const LAST_UPDATED = 'June 2026'

const sections = [
  {
    title: '1. Acceptance',
    body: `By accessing or using Get Your Fit ("GYF", "Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree, do not use the Service. GYF is currently in open beta — features may change, and uptime is not guaranteed at this stage. These Terms form a legal agreement between you and Get Your Fit.`,
  },
  {
    title: '2. Eligibility',
    body: `You must be at least 13 years old to use GYF (16 in the EEA). By using GYF, you confirm that you meet this requirement. If you are using GYF on behalf of a business or organisation, you represent that you have authority to bind that entity to these Terms.`,
  },
  {
    title: '3. Your Account',
    items: [
      { label: 'Registration', detail: 'You may be required to create an account to access certain features. You agree to provide accurate, current information and to keep it updated.' },
      { label: 'Security', detail: 'You are responsible for maintaining the confidentiality of your login credentials. Notify us immediately at security@getyourfit.app if you suspect unauthorised access.' },
      { label: 'One account per person', detail: 'You may not create multiple accounts to circumvent restrictions or abuse our systems.' },
    ],
  },
  {
    title: '4. What GYF Provides',
    body: `GYF is an AI-powered personal styling platform. We provide outfit recommendations, style analysis, and related features based on inputs you provide. GYF is a recommendation and discovery tool — it is not a retailer and does not sell clothing directly. Purchases are made through third-party retailers; we are not responsible for those transactions.`,
    items: [
      { label: 'Beta status', detail: 'GYF is in open beta. Features may be incomplete, unavailable, or change without notice. We are not liable for losses arising from beta limitations or downtime.' },
      { label: 'AI recommendations', detail: 'Recommendations are generated by AI models and may not always be accurate, suitable, or available. They are suggestions, not professional fashion or financial advice.' },
      { label: 'Affiliate links', detail: 'Some product links may be affiliate links. We may earn a commission if you make a purchase. This does not affect the price you pay or the independence of our recommendations.' },
    ],
  },
  {
    title: '5. Acceptable Use',
    body: `You agree not to:`,
    items: [
      { label: 'Abuse the platform', detail: 'Attempt to access, scrape, reverse-engineer, or interfere with GYF\'s systems, APIs, or models.' },
      { label: 'Upload harmful content', detail: 'Submit images or content that is illegal, abusive, hateful, sexually explicit, or violates the rights of others.' },
      { label: 'Misrepresent yourself', detail: 'Impersonate any person or entity, or falsely state or imply affiliation with GYF.' },
      { label: 'Circumvent security', detail: 'Attempt to bypass authentication, access other users\' data, or exploit vulnerabilities.' },
      { label: 'Spam or automate', detail: 'Use bots, scripts, or automated tools to interact with GYF in ways not expressly permitted.' },
    ],
    footer: 'Violation of these rules may result in immediate account suspension or termination.',
  },
  {
    title: '6. Your Content',
    body: `You retain ownership of any content you upload to GYF (including photos). By uploading content, you grant GYF a limited, non-exclusive licence to process and use that content solely to provide the Service to you. We do not sell your content or use it to train third-party models. See our Privacy Policy for full details on how photos are handled.`,
  },
  {
    title: '7. Intellectual Property',
    body: `All GYF software, designs, models, brand assets, and content created by GYF are the intellectual property of Get Your Fit. You may not copy, reproduce, distribute, or create derivative works from GYF's proprietary content without our written permission. The GYF name and logo are trademarks of Get Your Fit.`,
  },
  {
    title: '8. Third-Party Services',
    body: `GYF may link to or integrate with third-party websites, retailers, or services. We do not control these and are not responsible for their content, availability, or privacy practices. Your use of third-party services is subject to their own terms and policies.`,
  },
  {
    title: '9. Disclaimers',
    body: `GYF is provided "as is" and "as available" without warranties of any kind, express or implied. We do not warrant that the Service will be uninterrupted, error-free, or meet your specific requirements. Fashion recommendations are provided for informational and personal use only and do not constitute professional advice of any kind.`,
  },
  {
    title: '10. Limitation of Liability',
    body: `To the maximum extent permitted by applicable law, GYF and its directors, employees, and affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of — or inability to use — the Service. Our total cumulative liability to you shall not exceed the amount you paid us in the 12 months prior to the claim (or £50 if you have not paid anything).`,
  },
  {
    title: '11. Termination',
    body: `You may delete your account at any time from account settings. We may suspend or terminate your account at our discretion if you breach these Terms. Upon termination, your right to use the Service ceases immediately. Provisions that by their nature should survive termination (including intellectual property, disclaimers, and limitation of liability) will do so.`,
  },
  {
    title: '12. Changes to These Terms',
    body: `We may update these Terms as GYF evolves. We will notify you of material changes at least 14 days in advance by email or in-app notice. Continued use of GYF after the effective date constitutes your acceptance of the revised Terms.`,
  },
  {
    title: '13. Governing Law',
    body: `These Terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales, unless local consumer protection laws in your country require otherwise.`,
  },
  {
    title: '14. Contact',
    body: `For questions about these Terms:\n\nlegal@getyourfit.app\n\nGet Your Fit — open beta`,
  },
]

export default function TermsPage() {
  return (
    <div className="bg-white min-h-screen">
      <Navbar />

      <main className="max-w-3xl mx-auto px-5 sm:px-8 pt-32 sm:pt-40 pb-24 sm:pb-36">

        {/* Header */}
        <div className="mb-14 sm:mb-20">
          <div className="text-[0.68rem] font-mono text-[#6b6b78] uppercase tracking-[0.14em] mb-4">Legal</div>
          <h1 className="text-[clamp(2.2rem,5vw,3.5rem)] font-black text-[#111318] leading-[1.02] tracking-tight mb-4">
            Terms of Service
          </h1>
          <p className="text-[#9ca3af] text-sm font-mono">Last updated: {LAST_UPDATED}</p>
          <p className="text-[#5a5a65] text-base leading-[1.75] mt-6 font-[350]">
            Please read these Terms carefully before using GYF. They set out what you can expect from us and what we expect from you.
          </p>
        </div>

        {/* Sections */}
        <div className="space-y-12 sm:space-y-16 divide-y divide-black/[0.05]">
          {sections.map((s) => (
            <div key={s.title} className="pt-10 sm:pt-12 first:pt-0 first:border-0">
              <h2 className="text-base font-bold text-[#111318] mb-4 tracking-tight">{s.title}</h2>
              {s.body && (
                <p className="text-[#5a5a65] text-[0.9375rem] leading-[1.78] font-[350] whitespace-pre-line">
                  {s.body}
                </p>
              )}
              {s.items && (
                <ul className="mt-4 space-y-4">
                  {s.items.map((item) => (
                    <li key={item.label} className="flex gap-3">
                      <span className="w-1.5 h-1.5 rounded-full bg-[#111318]/20 flex-shrink-0 mt-[0.55rem]" />
                      <span className="text-[0.9375rem] text-[#5a5a65] leading-[1.78] font-[350]">
                        <strong className="text-[#111318] font-semibold">{item.label}:</strong>{' '}
                        {item.detail}
                      </span>
                    </li>
                  ))}
                </ul>
              )}
              {'footer' in s && s.footer && (
                <p className="mt-4 text-[0.9375rem] text-[#5a5a65] leading-[1.78] font-[350]">{s.footer}</p>
              )}
            </div>
          ))}
        </div>

        {/* Back link */}
        <div className="mt-16 pt-10 border-t border-black/[0.05] flex items-center gap-4">
          <Link href="/" className="text-sm font-medium text-[#5a5a65] hover:text-[#111318] transition-colors">
            ← Back to GYF
          </Link>
          <span className="text-black/10">·</span>
          <Link href="/privacy" className="text-sm font-medium text-[#5a5a65] hover:text-[#111318] transition-colors">
            Privacy Policy
          </Link>
        </div>
      </main>

      <Footer />
    </div>
  )
}
